data_rootdir: './dataset_root' 
audio_format: 'foa' #'mic'

dataset:
  name: 'TNSSE2020'
  labels: 
    - 'alarm'
    - 'crying baby'
    - 'crash'
    - 'barking dog'
    - 'running engine'
    - 'female scream'
    - 'female speech'
    - 'burning fire'
    - 'footsteps'
    - 'knocking on door'
    - 'male scream'
    - 'male speech'
    - 'ringing phone'
    - 'piano'
  clip_length: 60 
  label_resolution: 0.1 

features:
  sample_rate: 24000
  window: 'hann'
  n_fft: 1024
  hop_len: 600 
  n_mels: 256
  type: 'LogMel_IVs' # 'LogMel_GCCPHAT', 'LogLin_GCCPHAT', 'LogMel_IVs', 'LogLin_IVs', 'SALSA_FOA', 'SALSA_MIC'
  SALSA_window_size: 3
  SALSA_threshold: 5
  SS_TF_bin_filter: False
  train_chunklen_sec: 4
  train_hoplen_sec: 4
  test_chunklen_sec: 4
  test_hoplen_sec: 4
  augmentations: None

data augmentation:
  SpecAug:
    time_mask_num: 1
    time_mask_max_len: 35
    freq_mask_num: 1
    freq_mask_max_len: 30
  RC:
    time_mask_step: 50
    time_mask_max_len: 50
    freq_mask_max_len: 50    
  FS:
    freq_band_shift_range: 10
  ACS:
    p: 0.5
  p: 0.7

train:
  train_id: EINV2_tPIT_n1
  model: EINV2
  resume_model: # None_epoch_latest.pth
  loss_type: all
  loss_beta: 0.5
  batch_size: 32
  train_fold: 2,3,4,5,6
  valid_fold: 1
  overlap: 1,2
  optimizer: adamw
  lr: 0.0005
  lr_step_size: 80
  lr_gamma: 0.1
  max_epoch: 90
  threshold_sed: 0.5
  remark: None

inference:
  infer_id: EINV2_tPIT_n1
  testset_type: eval # dev | eval
  test_fold: None
  overlap: 1&2
  train_ids: EINV2_tPIT_n1
  models: EINV2
  batch_size: 64
  threshold_sed: 0.5
  remark: None
