data augmentation:
  SpecAug:
    time mask num: 1
    time mask max len: 35
    freq mask num: 1
    freq mask max len: 30
  RC:
    time mask step: 50
    time mask max len: 50
    freq mask max len: 50    
  FS:
    freq band shift range: 10
  ACS:
    p: 0.5
  p: 0.7

features:
  sample rate: 24000
  window: 'hann'
  n_fft: 1024
  hop_len: 600 
  n_mels: 256
  type: 'LogMel_IVs' # 'LogMel_GCCPHAT', 'LogLin_GCCPHAT', 'LogMel_IVs', 'LogLin_IVs', 'SALSA_FOA', 'SALSA_MIC'
  SALSA window size: 3
  SALSA threshold: 5
  SS TF bin filter: False

dataset:
  name: 'TNSSE2020'
  labels: 
    - 'alarm'
    - 'crying baby'
    - 'crash'
    - 'barking dog'
    - 'running engine'
    - 'female scream'
    - 'female speech'
    - 'burning fire'
    - 'footsteps'
    - 'knocking on door'
    - 'male scream'
    - 'male speech'
    - 'ringing phone'
    - 'piano'
  clip_length: 60 
  label_resolution: 0.1 
  fold_str_index: 4 
  ov_str_index: -1 

data rootdir: './dataset_root' 
audio format: 'foa' #'eval'

test: acs,specaug